# Generated by Django 3.1.5 on 2021-02-02 19:31

from django.db import migrations, models
import django.db.models.deletion
import util.fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', util.fields.fields.AutoKey(serialize=False)),
                ('street', models.CharField(max_length=31)),
                ('building', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', util.fields.fields.AutoKey(serialize=False)),
                ('description', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', util.fields.fields.AutoKey(serialize=False)),
                ('region', models.CharField(db_index=True, max_length=31)),
                ('city', models.CharField(db_index=True, max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', util.fields.fields.AutoKey(serialize=False)),
                ('number', models.IntegerField()),
                ('working', util.fields.fields.NotNullableFalseBoolean()),
                ('two_dim', util.fields.fields.NotNullableFalseBoolean()),
                ('three_dim', util.fields.fields.NotNullableFalseBoolean()),
                ('imax', util.fields.fields.NotNullableFalseBoolean()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('row_id', util.fields.fields.AutoKey(serialize=False)),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('CHP', 'Cheap'), ('REG', 'Medium'), ('VIP', 'VIP')], default='REG', max_length=15)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', util.fields.fields.AutoKey(serialize=False)),
                ('number', models.IntegerField()),
                ('serviceable', models.BooleanField(default=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.row')),
            ],
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('region', 'city'), name='unique_city'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.address'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.city'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('row', 'number'), name='unique_seat'),
        ),
        migrations.AddConstraint(
            model_name='row',
            constraint=models.UniqueConstraint(fields=('hall', 'number'), name='unique_row'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('cinema', 'number'), name='unique_hall'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('city', 'street', 'building'), name='unique_address'),
        ),
    ]
