# Generated by Django 3.1.5 on 2021-02-02 19:53

from django.db import migrations, models
import django.db.models.deletion
import util.fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', util.fields.fields.AutoKey(serialize=False)),
                ('title', models.CharField(db_index=True, max_length=63)),
                ('director', models.CharField(blank=True, max_length=63)),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=63)),
                ('premier', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', util.fields.fields.AutoKey(serialize=False)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('vip_price', models.IntegerField(db_index=True)),
                ('medium_price', models.IntegerField(db_index=True)),
                ('cheap_price', models.IntegerField(db_index=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('datetime', 'hall'), name='unique_show'),
        ),
    ]
